apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: foobarcomposition
  labels:
    provider: kubernetes
    guide: quickstart
spec:
  compositeTypeRef:
    apiVersion: managed.a-it.dev/v1alpha1
    kind: CompositeFoobar
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: "_" # will be replaced by the name of the Composite
                labels:
                  created-by: "foobar"
          providerConfigRef:
            name: kubernetes-provider
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.name"
          toFieldPath:  "spec.forProvider.manifest.metadata.name"
          transforms:
          - type: string
            string:
              type: Format
              fmt: 'crossplane-managed-%s'
