apiVersion: managed.a-it.dev/v1alpha1
kind: CompositeFoobar
metadata:
  name: toms-foo
  labels:
    managed-by: crossplane
    customLabel: "was_copied_by_composition"
spec:
  parameters:
    name: foo
    text: "Hello, Thomas!"
  compositionRef:
    name: foobarcomposition  # also default!
