apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositefoobars.managed.a-it.dev
spec:
  defaultCompositionRef:
    name: foobarcomposition
  group: managed.a-it.dev
  names:
    kind: CompositeFoobar
    plural: compositefoobars
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  name:
                    description: Name
                    type: string
                    enum: ["foo","bar"]
                  text:
                    type: string
                    default: "Hello, World!"
                required:
                - name
            required:
            - parameters