apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-system

helmCharts:
- name: crossplane
  repo: https://charts.crossplane.io/stable
  releaseName: crossplane
  namespace: crossplane-system
  includeCRDs: true
  version:  1.17.1
  valuesInline:
    # required for openshift
    securityContextCrossplane:
      runAsUser: null
      runAsGroup: null
    securityContextRBACManager:
      runAsUser: null
      runAsGroup: null
    provider.packages:
      xpkg.upbound.io/crossplane-contrib/provider-aws: v0.15.0

resources:
  - namespace.yaml
  - provider.yaml
  - providerconfig.yaml